name: Telegram News Bot

on:
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Debug workspace
        run: |
          echo "PWD:"
          pwd
          echo "LS:"
          ls -la
          echo "LS ROOT:"
          ls -la /home/runner/work
          echo "LS PROJECT:"
          ls -la /home/runner/work/telegram-news-bot
          echo "LS PROJECT ROOT:"
          ls -la /home/runner/work/telegram-news-bot/telegram-news-bot

      - name: Install dependencies (ABSOLUTE PATH)
        run: |
          python -m pip install --upgrade pip
          pip install -r /home/runner/work/telegram-news-bot/telegram-news-bot/requirements.txt

      - name: Run bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
          python bot/main.py
